import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,access,readdir} from 'node:fs/promises';
import path from 'node:path';
import {whatsappUrl,instagramUrl} from '../src/lib/contact.js';
import {site} from '../src/config/site.js';
const config={...site,whatsapp:'55 (11) 90000-0000',whatsappLink:''}; // número sintético: somente testes, nunca publicado
test('Contato ausente não gera destino falso',()=>{const blank={...site,whatsapp:'',whatsappLink:'',instagram:'',instagramLink:''};assert.equal(whatsappUrl(blank),'');assert.equal(instagramUrl(blank),'');});
test('WhatsApp codifica nome, acentos e caracteres reservados',()=>{const name='Caixa chá de bebê & amor + carinho';const url=new URL(whatsappUrl(config,name));assert.equal(url.pathname,'/5511900000000');assert.equal(url.searchParams.get('text'),`Olá! Vi no site da Mariella Personalizados o produto ${name} e gostaria de saber mais sobre valores e personalização.`);});
test('Contato aceita número, wa.me e API oficial',()=>{const expected=whatsappUrl(config);assert.equal(whatsappUrl({...config,whatsapp:'',whatsappLink:'https://wa.me/5511900000000?text=antigo'}),expected);assert.equal(whatsappUrl({...config,whatsapp:'',whatsappLink:'https://api.whatsapp.com/send?phone=5511900000000'}),expected);assert.throws(()=>whatsappUrl({...config,whatsappLink:'https://example.com/5511900000000'}));});
test('Instagram centralizado e seguro',()=>{assert.equal(instagramUrl({...site,instagram:'@perfil-de-teste',instagramLink:''}),'https://www.instagram.com/perfil-de-teste/');assert.throws(()=>instagramUrl({...site,instagramLink:'javascript:alert(1)'}));});
test('Link de catálogo WhatsApp vira conversa com mensagem do produto',()=>{const url=new URL(whatsappUrl({...config,whatsappLink:'https://wa.me/c/554184079838'},'Buquê azul'));assert.equal(url.pathname,'/554184079838');assert.ok(url.searchParams.get('text').includes('Buquê azul'));});
async function files(dir){const all=[];for(const item of await readdir(dir,{withFileTypes:true})){const p=path.join(dir,item.name);all.push(...(item.isDirectory()?await files(p):[p]));}return all;}
test('Todas as páginas possuem metadados e referências locais válidas',async()=>{const pages=(await files('dist')).filter(p=>p.endsWith('.html'));assert.ok(pages.length>=3);for(const file of pages){const html=await readFile(file,'utf8');for(const key of ['lang="pt-BR"','name="description"','rel="canonical"','property="og:image"','application/ld+json','<h1'])assert.ok(html.includes(key),`${file}: ${key}`);assert.equal((html.match(/<h1[ >]/g)||[]).length,1,file);for(const match of html.matchAll(/(?:src|href)="(\/[^"#?]*)/g)){const url=match[1];await access(path.join('dist',url.endsWith('/')?url+'index.html':url));}for(const match of html.matchAll(/<script type="application\/ld\+json">(.*?)<\/script>/gs))assert.doesNotThrow(()=>JSON.parse(match[1]));}});
test('Metadados dos produtos correspondem ao registro',async()=>{const products=JSON.parse(await readFile('src/data/products.json','utf8')).filter(p=>p.ativo);for(const p of products){const html=await readFile(`dist/produtos/${p.slug}/index.html`,'utf8');assert.ok(html.includes(`<title>${p.nome} | Mariella Personalizados</title>`));assert.ok(html.includes(site.domain+p.imagens[0].full));for(const im of p.imagens){await access(path.join('dist',im.src));await access(path.join('dist',im.full));}}});
